version: '3.8'

services:
  web:
    build: .
    container_name: web_app
    command: ["/app/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery


  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    command: celery -A tasks.tasks:celery worker --loglevel=info
    depends_on:
      - redis


  flower:
    build: .
    container_name: flower
    env_file:
      - .env
    command: celery -A tasks.tasks:celery flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
