version: '3.8'

services:
  web:
    build: .
    container_name: web_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A celery_app.app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  flower:
    build: .
    container_name: flower
    command: celery -A celery_app.app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379